Parcialdos/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="Administracion"),
    path('inventario/', include('inventario.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('stock.urls')),

    path('reconocimiento/', include('reconocimiento.urls')),

#     path('jet_api/', include('jet_django.urls')),
#     path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Parcialdos/carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns=[
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

Parcialdos/stock/urls.py
from xml.dom.minidom import Document
from django.urls import path
from stock import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="Home"),
    path('carrito', views.carrito, name="Carrito"),
    path('contacto', views.contacto, name="Contacto"),
    path('checkout', views.checkout, name="Checkout"),
    path('manual_usuario', views.manual_usuario, name="manual_usuario"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Parcialdos/stock/models.py
from django.db import models

Parcialdos/stock/views.py
from django.http import HttpResponse
from django.template import Template, Context
from django.template import loader
from django.shortcuts import render
from carro.carro import Carro
from inventario.models import articulos
from usuarios.models import usuarios
from carro.carro import Carro


# Create your views here.

def home(request):

    carro = Carro(request)

    arts = articulos.objects.all()

    ultimos_articulos=[]
    #print("################################################")
    if len(arts)>3:
        for i in range(len(arts)-4, len(arts)):
            ultimos_articulos.append(arts[i])
    else:
        for i in range(0, len(arts)):
            ultimos_articulos.append(arts[i])
        #print(ultimos_articulos)
    #print("################################################")
    return render(request, "stock/home.html", {"arts":arts, "articulos":ultimos_articulos})
    #return render(request, "stock/home.html")

def carrito(request):

    return render(request, "stock/carrito.html")

def contacto(request):

    return render(request, "stock/contacto.html")

def manual_usuario(request):

    return render(request, "stock/manual_usuario.html")

def checkout(request):
    info_usuario = usuarios.objects.all()
    pedido_valido = True
    return render(request, "stock/checkout.html", {"info_usuario":info_usuario, "pedido_valido": pedido_valido})
    # return render(request, "stock/checkout.html", {"info_usuario":info_usuario})

Parcialdos/stock/templates/stock/base.html
{% load static %}
{% load admin_urls %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'stock/img/chems-usac.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	{% if request.path == '/' %}
	<title>Sonrisas de Vida</title>
	{% elif request.path == '/inventario/' %}
	<title>Consultas</title>
	{% elif request.path == '/carrito' %}
	<title>Consultas</title>
	{% elif request.path == '/contacto' %}
	<title>Contacto</title>
	{% elif request.path == '/checkout' %}
	<title>Checkout</title>
	{% elif request.path == '/autenticacion/' %}
	<title>Registro</title>
	{% elif request.path == '/autenticacion/iniciar_sesion' %}
	<title>Iniciar sesión</title>
	{% elif request.path == '/autenticacion/perfil' %}
	<title>Perfil</title>
	{% elif request.path == '/autenticacion/reset_password/' %}
	<title>Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset_password_sent/' %}
	<title>Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset/Mw/set-password/' %}
	<title>Recuperar cuenta</title>
	{% elif request.path == '/autenticacion/reset_password_complete/' %}
	<title>Recuperar cuenta</title>
	{% else %}
	<title>Producto</title>
	{% endif %}
	<!-- CSS ============================================= -->
	<link rel="stylesheet" href="{% static 'stock/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/ion.rangeSlider.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/ion.rangeSlider.skinFlat.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'stock/css/main.css' %}">
</head>

<body class="Bodyss">

	<!-- Start Header Area -->
	<header class="header_area sticky-header" style="background-color:#74bec1;">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box" style="background-color:#adebbe;">
				<div class="container" style="background-color:#516091;">
					<a class="navbar-brand logo_h" href="{% url 'Home' %}"><img src="{% static 'stock/img/logop.svg' %}" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
						aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #adebbe;">
						<span class="icon-bar" style="background-color:#adebbe;"></span>
						<span class="icon-bar" style="background-color:#adebbe;"></span>
						<span class="icon-bar" style="background-color:#adebbe;"></span>
					</button>
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent" style="background-color:#516091;">
						<ul class="nav navbar-nav menu_nav ml-auto" style="background-color: #516091;">
							<li class="nav-item {% if request.path == '/' %}active{% endif %}"><a class="nav-link" href="{% url 'Home' %}" style="color: #ffffff">Inicio</a></li>
							<li class="nav-item {% if request.path == '/contacto' %}active{% endif %}"><a class="nav-link" href="{% url 'Contacto' %}" style="color: #ffffff">Contacto</a></li>
							<li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
									aria-expanded="false" style="color: #ffffff">Consultas</a>
								<ul class="dropdown-menu">
									<li class="nav-item {% if request.path == '/inventario/' %}active{% endif %}"><a class="nav-link" href="{% url 'Catalogo' %}" style="color: #ffffff">Servicios</a></li>
									<li class="nav-item {% if request.path == '/carrito' %}active{% endif %}"><a class="nav-link" href="{% url 'Carrito' %}" style="color: #ffffff">Pedir Cita</a></li>
								</ul>
							</li>
							{% if user.is_authenticated %}
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
									aria-expanded="false">{{ user.username }}</a>
									<ul class="dropdown-menu">
										{% if user.is_staff is not True %}
											<li class="nav-item {% if request.path == '/autenticacion/perfil' %}active{% endif %}"><a class="nav-link" href="{% url 'perfil' %}" style="color: #ffffff">Mi perfil</a></li>
										{% else %}
											<li class="nav-item {% if request.path == '/autenticacion/perfil' %}active{% endif %}"><a class="nav-link" href="{% url 'admin:index' %}" style="color: #ffffff">Administración</a></li>
										{% endif %}
										<li class="nav-item"><a class="nav-link" href="{% url 'cerrar_sesion' %}" style="color: #ff4949">Cerrar sesión</a></li>
									</ul>
								</li>
							{% else %}
								<li class="nav-item submenu dropdown" style="color: #516091">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
									aria-expanded="false" style="color: #ffffff">Iniciar sesión</a>
									<ul class="dropdown-menu">
										<li class="nav-item {% if request.path == '/autenticacion/' %}active{% endif %}"><a class="nav-link" href="{% url 'Autenticacion' %}" style="color: #ffffff;">Registrarse</a></li>
										<li class="nav-item {% if request.path == '/autenticacion/iniciar_sesion' %}active{% endif %}"><a class="nav-link" href="{% url 'iniciar_sesion' %}" style="color: #f5f5f5;">Iniciar sesión</a></li>
										<li class="nav-item {% if request.path == '/autenticacion/reset_password/' %}active{% endif %}"><a class="nav-link" href="{% url 'reset_password' %}" style="color: #ffffff;">Recuperar cuenta</a></li>
									</ul>
								</li>
							{% endif %}
						</ul>
	
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"><a class="cart"><span class="ti-user" style="color: rgb(255, 255, 255);"> </span></a></li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Buscar Aquí">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Cerrar Búsqueda"></span>
				</form>
			</div>
		</div>
	</header>
	<!-- End Header Area -->

	<!-- Start changed Area -->
	{% block content %}
	{% endblock %}
	<!-- End changed Area -->

<!-- Start footer Area -->
<footer class="footer-area section_gap" style="background-color: #333333;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 style="color: #ffffff;">Sobre Nosotros</h6>
                    <p style="color: #ffffff;">
                        En Sonrisas de Vida, nos dedicamos a brindar el mejor cuidado para el bienestar y la salud de tus pequeños. Nuestro equipo de especialistas está comprometido en acompañar cada etapa de su crecimiento, ofreciendo un entorno seguro, amable y lleno de cariño. Creemos que cada niño merece una atención personalizada y de calidad, para que puedan crecer sanos, felices y llenos de sonrisas.
                    </p>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 style="color: #ffffff;">Redes Sociales</h6>
                    <p style="color: #ffffff;">¡Síguenos en nuestras redes sociales y mantente al tanto de nuestros consejos de salud infantil, eventos especiales y promociones! Juntos, haremos que cada visita sea una experiencia positiva y llena de sonrisas para tus pequeños.</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#" style="color: #1877F2; font-size: 20px; margin-right: 10px;">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a href="#" style="color: #1DA1F2; font-size: 20px;">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0" style="color: #ffffff;">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los Derechos Reservados
            </p>
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'stock/js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
 crossorigin="anonymous"></script>
<script src="{% static 'stock/js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'stock/js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'stock/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'stock/js/jquery.sticky.js' %}"></script>
<script src="{% static 'stock/js/nouislider.min.js' %}"></script>
<script src="{% static 'stock/js/countdown.js' %}"></script>
<script src="{% static 'stock/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'stock/js/owl.carousel.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'stock/js/gmaps.min.js' %}"></script>
<script src="{% static 'stock/js/main.js' %}"></script>
</body>
</html>

Parcialdos/stock/templates/stock/carrito.html
{% extends "stock/base.html"%}

{% load static %}
{% block content %}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Carrito</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'Home' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<!--<a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>-->
						<a href="{% url 'Carrito' %}">Carrito</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

    {% if request.user.is_authenticated %}

        <!--================Cart Area =================-->
        <section class="cart_area">
            <div class="container">
                <div class="cart_inner">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Producto</th>
                                    <th scope="col">Precio unitario</th>
                                    <th scope="col">Cantidad</th>
                                    <th scope="col">Subotal</th>
                                </tr>
                            </thead>
                            <tbody>                                

                                {% if request.session.carro.items %}
                                    {% for key, value in request.session.carro.items %}

                                    <!--================Inicio Producto Individual =================-->
                                    <tr>
                                        <td>
                                            <div class="media">
                                                <div class="d-flex">
                                                    <img src="{{value.imagen}}" alt="" style="width: 50px; ">
                                                </div>
                                                <div class="media-body">
                                                    <p>{{value.nombre}}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <h5 style="color: black;">Q{{value.precio }}</h5>
                                        </td>
                                        <td>
                                            <div class="product_count">
                                                <input type="text" name="qty" id="sst" maxlength="12" value="{{value.cantidad}}" title="Quantity:"
                                                    class="input-text qty">
                                                <form action="{%url 'carro:agregar' value.producto_id%}">
                                                    <button type="submit" class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                                                </form>
                                                
                                                {% if value.cantidad > 1%}
                                                    <form action="{%url 'carro:restar' value.producto_id%}">
                                                        <button type="submit" class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                                                    </form>
                                                {% else %}
                                                    <button type="submit" class="reduced items-count" type="button" data-toggle="modal" data-target="#exampleModal"><i class="lnr lnr-chevron-down"></i></button>
                                                {%endif%}
                                                
                                            </div>
                                        </td>
                                        <td>
                                            <h5 style="color: black;">Q{{value.subtotal}}</h5>
                                        </td>
                                    </tr>
                                    <!--================Fin Producto Individual =================-->
                                    <!--================INICIO MODAL =================-->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confimarción de eliminación</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                </div>
                                                <div class="modal-body">
                                                ¿Ésta seguro de eliminar este producto de su carrito?
                                                </div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Regresar</button>
                                                <form action="{%url 'carro:restar' value.producto_id%}">
                                                    <button type="submit" type="button" class="btn btn-primary">Confirmar</button>
                                                </form>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    <!--================FIN MODAL =================-->

                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="4">
                                            <div class="alert alert-danger text-center">
                                                Sin productos en el carrito
                                            </div>
                                        </td>
                                    </tr>
                                {% endif %}


                                <tr class="bottom_button">
                                    <td>
                                        <a class="gray_btn" href="{% url 'Carrito' %}">Actualizar carrito</a>
                                    </td>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>
                                        <div class="cupon_text d-flex align-items-center" style="float: right;">
                                            <input type="text" placeholder="Código de cupón">
                                            <a class="primary-btn" href="#">Aplicar</a>
                                            <!--<a class="gray_btn" href="{% url 'Carrito' %}">Cancelar</a>-->
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>
                                        <h5 style="color: black;">Total</h5>
                                    </td>
                                    <td>
                                        <h5 style="color: black;">Q{{importe_total_carro}}</h5>
                                    </td>
                                </tr>
                                <tr class="shipping_area">
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>
                                        <h5>Envio</h5>
                                    </td>
                                    <td>
                                        <div class="shipping_box">
                                            <ul class="list">
                                                <li class="active"><a>Gratis</a></li>
                                            </ul>
                                            
                                        </div>
                                    </td>
                                </tr>
                                <tr class="out_button_area">
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>
                                        <div class="checkout_btn_inner d-flex align-items-center" style="float: right;">
                                            <a class="gray_btn" href="{% url 'Catalogo' %}">Volver a catálogo</a>
                                            {% if request.session.carro.items %}
                                                <a class="primary-btn" href="{% url 'Checkout' %}">Pagar</a>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Cart Area =================-->
    
    {% else %}
        <br></br>
        <div class="alert alert-danger text-center">Debe iniciar sesión</div>
        <br></br>
    {% endif %}


{% endblock %}

Parcialdos/stock/templates/stock/contacto.html
{% extends "stock/base.html" %}
{% load static %}
{% block content %}
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1 style="color:rgb(0, 0, 0);">Contacto</h1>
                    <nav class="d-flex align-items-center">
                        <a href="{% url 'Home' %}" style="color:rgb(0, 0, 0);">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="{% url 'Contacto' %}" style="color:rgb(0, 0, 0);">Contacto</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->
    <hr>

    <!--================Contact Area =================-->
    <section class="contact_area section_gap_bottom">
        <div class="container" style="background-color: #ffffff;">
            <div class="row justify-content-center">
                <div class="contact_info">
                    <!-- Nuevo apartado del horario de atención -->
                    <div class="info_item">
                        <i class="lnr lnr-clock" style="color:rgb(0, 0, 0);"></i>
                        <h6 style="color: rgb(0, 0, 0);">Horario de Atención</h6>
                        <p style="color: #555555;">Lunes a Viernes: 15:00 - 18:30 Horas<br>Sábado: 09:00 - 13:00 Horas</p>
                    </div>
                    <!-- Fin del horario de atención -->

                    <div class="info_item">
                        <i class="lnr lnr-home" style="color:rgb(0, 0, 0);"></i>
                        <h6 style="color: rgb(0, 0, 0);">Ciudad de Guatemala</h6>
                        <p style="color: #555555;">3 Calle 9-80, Centro Comercial Plaza Médica, Local 19, Ciudad San Cristobal, Zona 8 de Mixco</p>
                    </div>

                    <!-- Aquí colocamos el mapa -->
                    <div class="info_item" style="z-index: 0; position: relative;">
                        <div id="map" style="height: 400px; width: 100%; background-color: #fff;"></div>
                    </div>
                    <!-- Fin del mapa -->

                    <div class="info_item">
                        <i class="lnr lnr-phone-handset" style="color:rgb(0, 0, 0);"></i>
                        <h6 style="color: rgb(0, 0, 0);">(502) 2480-8679<br>(502) 2480-8680</h6>
                        <p style="color: #555555;">Horario de Atención Telefónica: 8:00 - 19:00 Hrs</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope" style="color:rgb(0, 0, 0);"></i>
                        <h6 style="color: rgb(0, 0, 0);">info@drablandinanutriologa.com</h6>
                        <p style="color: #555555;">Disponible las 24h</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Contact Area =================-->
    <hr>

    <!-- Leaflet.js y script para el mapa -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script>
        // Inicializar el mapa y establecer la vista en las nuevas coordenadas
        const map = L.map('map').setView([14.608145848278175, -90.58825434784433], 15);

        // Añadir la capa de OpenStreetMap
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap contributors'
        }).addTo(map);

        // Añadir un marcador en la nueva ubicación
        const marker = L.marker([14.608145848278175, -90.58825434784433]).addTo(map);

        // Añadir un popup al marcador con la nueva información
        marker.bindPopup("<b>Plaza Médica, Local 19</b><br>Ciudad San Cristobal, Mixco").openPopup();
    </script>
{% endblock %}